apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "iqserver.fullname" . }}
  labels:
    app: {{ template "iqserver.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "iqserver.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "iqserver.fullname" . }}
    spec:
      {{- if .Values.iqserver.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.iqserver.imagePullSecret }}
      {{- end }}
      containers:
      - name: {{ template "iqserver.fullname" . }}
        image: {{ .Values.iqserver.imageName }}:{{ .Values.iqserver.imageTag }}
        ports:
        - containerPort: {{ .Values.iq.applicationPort }}
        {{- if .Values.deployment.terminationGracePeriodSeconds }}
        terminationGracePeriodSeconds: {{ .Values.deployment.terminationGracePeriodSeconds }}
        {{- end }}
        lifecycle:
          {{- if .Values.deployment.postStart.command }}
          postStart:
            exec:
              command: {{ .Values.deployment.postStart.command }}
          {{- end }}
          {{- if .Values.deployment.preStart.command }}
          preStart:
            exec:
              command: {{ .Values.deployment.preStart.command }}
          {{- end }}
        resources:
          limits:
            memory: {{ .Values.iq.memory }}
        volumeMounts:
          - mountPath: /sonatype-work
            name: nxiq-pv-storage
          - mountPath: /etc/nexus-iq-server
            name: config-volume
          - mountPath: /etc/nexus-iq-license
            name: license-volume
      volumes:
        - name: nxiq-pv-storage
          persistentVolumeClaim:
            claimName: nxiq-pv-claim
        - name: config-volume
          configMap:
            name: {{ template "iqserver.fullname" . }}
            items:
              - key: config.yml
                path: config.yml
        - name: license-volume
          secret:
            secretName: {{ template "iqserver.fullname" . }}
