apiVersion: v1
kind: Service
metadata:
  name: {{ template "iqserver.fullname" . }}
spec:
  selector:
    app: {{ template "iqserver.fullname" . }}
  ports:
  - name: application
    port: {{ .Values.iq.applicationPort }}
  - name: admin
    port: {{ .Values.iq.adminPort }}
  type: ClusterIP
  