apiVersion: v1
appVersion: 1.87.0
description: A Helm chart for Kubernetes
name: iqserver
version: 0.1.1
description: Sonatype Nexus IQ Server continuously monitors your entire software supply chain
keywords:
  - sonatype
  - nexus
  - lifecycle
  - iq
  - remediate
  - vulnerabilities
  - policy
home: https://www.sonatype.com/nexus-iq-server
icon: https://www.sonatype.com/hubfs/2019%20Horizontal%20Product%20logo/horizontal%20Repo%20/Repo/NexusRepo_horiz.svg
maintainers:
  - email:  cloud-ops@sonatype.com
    name: Sonatype
